### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by jay-wilkinson** [laszlodaniel/ChryslerScanner#5]
The link on page https://github.com/laszlodaniel/ChryslerCCDSCIScanner/tree/master/Arduino/GettingStarted , in the main sketch, etc. seems to be dead. (https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads/)

**Comment by laszlodaniel** [comment]
Thanks for letting me know! The Arduino sketch structure changed since then and the library was replaced by another one. You can download the current I2C LCD library from here:
https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library

The same link can be found in the lcd.h file. I also updated the link in the Getting started section.

**Comment by jay-wilkinson** [comment]
Thanks for the quick response!
